#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# SSH Shell Menu
# Version 1.0
# Written by Maximilian Thoma 2019
#
# ssm      is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#

import locale
from dialog import Dialog
import os
from os.path import expanduser
import configparser


def main():

    locale.setlocale(locale.LC_ALL, '')

    config = configparser.ConfigParser()
    config.read(expanduser("~")+'/.ssm/connections.ini')

    profiles = {}

    for c in config:
        if len(dict(config[c])) > 0:
            profiles[c] = dict(config[c])

    while 1:

        d = Dialog(dialog="dialog")
        d.set_background_title("SSH Shell Menu")

        choices = []

        for name, settings in profiles.items():
            choices.append((name, settings['description']))

        choices.sort()

        code, tag = d.menu("Choose connection:", choices=choices)

        if code == d.OK:

            if len(profiles[tag]['ssh_key']) > 0:

                os.system("clear; ssh %s@%s -p %s -i %s %s" %
                          (profiles[tag]['user'],
                           profiles[tag]['server'],
                           profiles[tag]['port'],
                           profiles[tag]['ssh_key'],
                           profiles[tag]['options'],))

            else:
                os.system("clear; ssh %s@%s -p %s %s" %
                          (profiles[tag]['user'],
                           profiles[tag]['server'],
                           profiles[tag]['port'],
                           profiles[tag]['options'],))

        if code == d.CANCEL:
            os.system("clear")
            break


if __name__ == "__main__":
    main()
